default: &default
  public_certificate_path: './config/certificates/app_public.pem'

test:
  <<: *default
  private_certificate_path: './spec/test_certificates/app_private.pem'
  public_certificate_path: './spec/test_certificates/app_public.pem'

production:
  <<: *default
