default: &default
  host: 'https://priora.saltedge.com/api/connectors/v2'
  certificate_path: './config/certificates/salt_edge.pem'

development:
  <<: *default

test:
  <<: *default
  certificate_path: './spec/test_certificates/salt_edge_public.pem'

production:
  <<: *default
