default: &default
  host: 'http://salt_edge.demo/api/connectors/v2'

development:
  <<: *default
  certificate_path: './config/certificates/salt_edge.pem'

test:
  <<: *default
  certificate_path: './spec/test_certificates/salt_edge_public.pem'
